###GET ALL ADS
GET http://localhost:4000/api/ads

###ADD ADS
POST http://localhost:4000/api/ads/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTcwMDUyNDg1NTIwOSwiaWF0IjoxNzAwNTI0ODU1LCJleHAiOjE3MDA2MTEyNTV9.pFCOtVwt0YblQpF4Qu3GopvA2JCVnbhwaruUXMrPDU4

{
  "title": "proba reklama",
  "body": "Tekst reklame",
  "image": "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg?w=2000",
  "startDate": "2023-10-27T16:36:06.839Z",
  "endDate": "2023-11-15T16:36:06.839Z",
  "price": 500,
  "duration": "6"
}

###PAYMENT INIT
POST http://localhost:4000/api/ads/paymentInit
Content-Type: application/json

{
  "price": 500,
  "currency": "usd"
}