### ADD MESSAGE
POST http://localhost:4000/api/messages/addMessage/646e520b4611dc2bdddb7b7e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTY5ODQyNjM1OTEwOCwiaWF0IjoxNjk4NDI2MzU5LCJleHAiOjE2OTg1MTI3NTl9.nHA0OZEJm7pymT3Yc5pssSrXCM6_Fn1kg9CEMZx3ux4

{
  "message": "Test porukaa !!!"
}

### GET SENT MESSAGES
GET http://localhost:4000/api/messages/sentMessages
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTY5ODQyNjM1OTEwOCwiaWF0IjoxNjk4NDI2MzU5LCJleHAiOjE2OTg1MTI3NTl9.nHA0OZEJm7pymT3Yc5pssSrXCM6_Fn1kg9CEMZx3ux4

### GET RECEIVED MESSAGES
GET http://localhost:4000/api/messages/receivedMessages
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTY5ODQyNjM1OTEwOCwiaWF0IjoxNjk4NDI2MzU5LCJleHAiOjE2OTg1MTI3NTl9.nHA0OZEJm7pymT3Yc5pssSrXCM6_Fn1kg9CEMZx3ux4