### GET ALL USER
GET http://localhost:4000/api/user

### 
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
  "firstName": "Dejan",
  "lastName": "Zivkovic"
}

###
PUT http://localhost:4000/api/user/update/646e520b4611dc2bdddb7b7e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTY5ODAwMjE3OTU4NCwiaWF0IjoxNjk4MDAyMTc5LCJleHAiOjE2OTgwODg1Nzl9.nJKbLQPOI9t7pBNYkTZvQjRkROa02LQL8vcjFs22eUQ


{
  "firstName": "Marko",
  "lastName": "Petric",
  "gender": "male",
  "role": "user"
}

### DELETE USER
DELETE http://localhost:4000/api/user/delete/647e5e98f4dca2c15c847f7e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdlNjI3ZjIyNGMyNTViYjViM2QzZWMiLCJmaXJzdE5hbWUiOiJEemVuYWQiLCJsYXN0TmFtZSI6IkNhdGljIiwicm9sZSI6InVzZXIiLCJ0aW1lIjoxNjg2MDA0MzU0MDg5LCJpYXQiOjE2ODYwMDQzNTQsImV4cCI6MTY4NjA5MDc1NH0.efTwW_UjvAJRwLx2RigC-moNuUNIm3HRJrFKd-5u9sw